### ISSUE TITLE
Is this the active repo?

### ISSUE THREAD

**Issue by tleen** [northernbeacheswebsites/wp-gotowebinar#1]
This seems outdated vs the current plugin version of 8.9. Is this not an active repo?

**Comment by northernbeacheswebsites** [comment]
Hi Tom,

This isn’t an active repo. I recall putting the plugin on Github at some point because I was seeing whether Github was something I wanted to use. But I couldn’t really work out a nice workflow to use this with WordPress and so far I haven’t had any interest in people wanted to contribute to the code. This was the first plugin I developed, so now when I look back on it there would be a lot of things I would change myself. Cheers, 

Martin Gibson  | Designer
Northern Beaches Websites

**Comment by tleen** [comment]
I had the same problem too doing WordPress plugins + github! [I took some notes](http://www.codesiderations.com/2014/08/25/using-git-and-subversion-with-wordpress-plugins.html) when I was able to work it out if it helps. 

Probably worth dropping a note in the readme for this repo that it is no longer valid & the wordpress plugin support is the place to be.

Thanks for the plugin, appreciate the work!
